import { EntityManager } from '@mikro-orm/core'
import { Seeder } from '@mikro-orm/seeder'
import { WORD_CATEGORY_SLUG, WordCategory } from '../modules/words/word-category.entity'
import { Word } from '../modules/words/words.entity'

const BASE_WORDS = [
  'Afrique',
  'Aiguille',
  'Aile',
  'Air',
  'Alien',
  'Allemagne',
  'Alpes',
  'Amour',
  'Ampoule',
  'Amérique',
  'Ange',
  'Angleterre',
  'Anneau',
  'Appareil',
  'Araignée',
  'Arc',
  'Argent',
  'Asile',
  'Astérix',
  'Atlantique',
  'Atout',
  'Australie',
  'Avion',
  'Avocat',
  'Baguette',
  'Baie',
  'Balance',
  'Baleine',
  'Balle',
  'Ballon',
  'Banane',
  'Banc',
  'Bande',
  'Banque',
  'Bar',
  'Barbe',
  'Base',
  'Bateau',
  'Berlin',
  'Bière',
  'Blé',
  'Bombe',
  'Bon',
  'Botte',
  'Bouche',
  'Bouchon',
  'Bougie',
  'Boulet',
  'Bourse',
  'Bouteille',
  'Bouton',
  'Boîte',
  'Branche',
  'Bretelle',
  'Brique',
  'Bureau',
  'But',
  'Bâton',
  'Bête',
  'Bûche',
  'Bɶuf',
  'Cabinet',
  'Cadre',
  'Cafard',
  'Café',
  'Camembert',
  'Campagne',
  'Canada',
  'Canard',
  'Canne',
  'Canon',
  'Carreau',
  'Carrière',
  'Carte',
  'Carton',
  'Cartouche',
  'Casino',
  'Ceinture',
  'Cellule',
  'Centre',
  'Cercle',
  'Champ',
  'Champagne',
  'Chance',
  'Chapeau',
  'Charge',
  'Charme',
  'Chasse',
  'Chat',
  'Chausson',
  'Chaîne',
  'Chef',
  'Chemise',
  'Cheval',
  'Chevalier',
  'Chien',
  'Chine',
  'Chocolat',
  'Chou',
  'Château',
  'Cinéma',
  'Cirque',
  'Citrouille',
  'Classe',
  'Club',
  'Clé',
  'Cochon',
  'Code',
  'Col',
  'Colle',
  'Commerce',
  'Coq',
  'Corde',
  'Corne',
  'Coton',
  'Coupe',
  'Courant',
  'Couronne',
  'Course',
  'Court',
  'Couteau',
  'Couverture',
  'Critique',
  'Crochet',
  'Cuisine',
  'Cycle',
  'Cɶur',
  'Danse',
  'Dinosaure',
  'Docteur',
  'Don',
  'Dragon',
  'Droit',
  'Droite',
  'Eau',
  'Enceinte',
  'Ensemble',
  'Entrée',
  'Espace',
  'Espagne',
  'Espion',
  'Esprit',
  'Essence',
  'Europe',
  'Facteur',
  'Fantôme',
  'Farce',
  'Fer',
  'Ferme',
  'Feu',
  'Feuille',
  'Figure',
  'Filet',
  'Fin',
  'Flûte',
  'Formule',
  'Fort',
  'Forêt',
  'Fou',
  'Foyer',
  'Fraise',
  'Français',
  'Front',
  'Fuite',
  'Garde',
  'Gauche',
  'Gel',
  'Glace',
  'Gorge',
  'Grain',
  'Grenade',
  'Grue',
  'Grèce',
  'Guerre',
  'Guide',
  'Géant',
  'Génie',
  'Herbe',
  'Himalaya',
  'Histoire',
  'Hiver',
  'Hollywood',
  'Héros',
  'Hôpital',
  'Hôtel',
  'Indien',
  'Iris',
  'Jet',
  'Jeu',
  'Jour',
  'Journal',
  'Jumelles',
  'Jungle',
  'Kangourou',
  'Kiwi',
  'Lait',
  'Langue',
  'Laser',
  'Lentille',
  'Lettre',
  'Licorne',
  'Lien',
  'Ligne',
  'Lion',
  'Liquide',
  'Lit',
  'Livre',
  'Londres',
  'Louche',
  'Lumière',
  'Lune',
  'Lunettes',
  'Luxe',
  'Machine',
  'Magie',
  'Main',
  'Majeur',
  'Maladie',
  'Manche',
  'Manège',
  'Marche',
  'Marin',
  'Marque',
  'Marron',
  'Mars',
  'Maîtresse',
  'Membre',
  'Menu',
  'Meuble',
  'Microscope',
  'Miel',
  'Millionaire',
  'Mine',
  'Mineur',
  'Mode',
  'Molière',
  'Mort',
  'Mouche',
  'Moule',
  'Mousse',
  'Moustache',
  'Mémoire',
  'Nain',
  'Napoléon',
  'Neige',
  'New-York',
  'Ninja',
  'Noir',
  'Note',
  'Noël',
  'Nuit',
  'Numéro',
  'Nɶud',
  'Oiseau',
  'Opéra',
  'Opération',
  'Or',
  'Orange',
  'Ordre',
  'Page',
  'Paille',
  'Palais',
  'Palme',
  'Papier',
  'Parachute',
  'Paris',
  'Partie',
  'Passe',
  'Patron',
  'Pendule',
  'Pensée',
  'Perle',
  'Peste',
  'Phare',
  'Physique',
  'Piano',
  'Pied',
  'Pigeon',
  'Pile',
  'Pilote',
  'Pingouin',
  'Pirate',
  'Pièce',
  'Place',
  'Plage',
  'Plan',
  'Planche',
  'Plante',
  'Plat',
  'Plateau',
  'Plume',
  'Point',
  'Poire',
  'Poison',
  'Poisson',
  'Police',
  'Pomme',
  'Pompe',
  'Portable',
  'Poste',
  'Pouce',
  'Poêle',
  'Princesse',
  'Prise',
  'Prêt',
  'Pyramide',
  'Pétrole',
  'Pêche',
  'Pôle',
  'Quartier',
  'Queue',
  'Radio',
  'Raie',
  'Rame',
  'Rat',
  'Rayon',
  'Recette',
  'Reine',
  'Religieuse',
  'Remise',
  'Requin',
  'Restaurant',
  'Robe',
  'Robot',
  'Roi',
  'Rome',
  'Ronde',
  'Rose',
  'Rouge',
  'Rouleau',
  'Roulette',
  'Russie',
  'Règle',
  'Résistance',
  'Révolution',
  'Sardine',
  'Satellite',
  'Schtroumpf',
  'Science',
  'Scène',
  'Sens',
  'Sept',
  'Serpent',
  'Sirène',
  'Siège',
  'Sol',
  'Soldat',
  'Soleil',
  'Solution',
  'Somme',
  'Sorcière',
  'Sortie',
  'Souris',
  'Table',
  'Tableau',
  'Talon',
  'Tambour',
  'Temple',
  'Temps',
  'Tennis',
  'Terre',
  'Timbre',
  'Titre',
  'Toile',
  'Tokyo',
  'Tour',
  'Trait',
  'Trou',
  'Trésor',
  'Tube',
  'Tuile',
  'Tête',
  'Uniforme',
  'Vague',
  'Vaisseau',
  'Vampire',
  'Vase',
  'Vent',
  'Verre',
  'Vert',
  'Vie',
  'Vin',
  'Visage',
  'Vision',
  'Voile',
  'Voiture',
  'Vol',
  'Voleur',
  'Volume',
  'Zéro',
  'Échelle',
  'Éclair',
  'École',
  'Égalité',
  'Égypte',
  'Éponge',
  'Étoile',
  'Étude',
  'Œil',
  'Œuf',
]

const MUSIC_ARTISTS_FR_WORDS = [
  'Édith Piaf',
  'Jean‐Michel Jarre',
  'Johnny Hallyday',
  'Charles Aznavour',
  'Dalida',
  'Serge Gainsbourg',
  'Mylène Farmer',
  'Françoise Hardy',
  'Mireille Mathieu',
  'Justice',
  'Air',
  'Georges Brassens',
  'France Gall',
  'Renaud',
  'Manu Chao',
  'Gojira',
  'DJ Snake',
  'Sylvie Vartan',
  'Léo Ferré',
  'Indochine',
  'Phoenix',
  'Alizée',
  'Yann Tiersen',
  'Claude François',
  'Alain Bashung',
  'Yves Montand',
  'Joe Dassin',
  'Noir Désir',
  'Gipsy Kings',
  'Michel Sardou',
  'Patricia Kaas',
  'Jane Birkin',
  'Michel Polnareff',
  'Bob Sinclar',
  'Gilbert Bécaud',
  'Booba',
  'Alain Souchon',
  'Zazie',
  'Christine and the Queens',
  'Brigitte Bardot',
  'M. Pokora',
  'Charlotte Gainsbourg',
  'GIMS',
  'IAM',
  'Boris Vian',
  'Laurent Garnier',
  'Barbara',
  'Étienne Daho',
  'Zaz',
  'Jul',
  'Daniel Balavoine',
  'Bernard Lavilliers',
  'Charles Trenet',
  'Jacques Higelin',
  'Eddy Mitchell',
  'Jacques Dutronc',
  'Sheila',
  'Julien Clerc',
  'Christophe',
  'Lorie',
  'Mr. Oizo',
  'Claude Nougaro',
  'Florent Pagny',
  'Ibrahim Maalouf',
  'Henri Salvador',
  'Vanessa Paradis',
  'Calogero',
  'Jean‐Jacques Goldman',
  'Martin Solveig',
  'Enrico Macias',
  'Marc Lavoine',
  'Caravan Palace',
  '‐M‐',
  'Bourvil',
  'Anne Sylvestre',
  'Véronique Sanson',
  'Benjamin Biolay',
  'Camille',
  'Brigitte Fontaine',
  'Pascal Obispo',
  'Patrick Bruel',
  'Les Rita Mitsouko',
  'Francis Cabrel',
  'Yelle',
  'Pomme',
  'Michel Fugain',
  'Sébastien Tellier',
  'La Fouine',
  'Yannick Noah',
  'Era',
  'Tri Yann',
  'Shy’m',
  'Serge Lama',
  'MC Solaar',
  'Aya Nakamura',
  'Dorothée',
  'Pierre Perret',
  'Laurent Voulzy',
  'Michel Delpech',
  'Vitalic',
  'Suprême NTM',
  'Louane',
  'Michel Berger',
  'Hélène Ségara',
  'Woodkid',
  'Raphaël',
  'Jenifer',
  'Mano Negra',
  'Jain',
  'Michel Jonasz',
  'Superbus',
  'Les Ogres de Barback',
  'Nolwenn Leroy',
  'Petit Biscuit',
  'La Femme',
  'Patrick Fiori',
  'Vitaa',
  'Louise Attaque',
  'Amel Bent',
  'Julien Doré',
  'Bérurier Noir',
  'Saez',
  'Katerine',
  'Christophe Maé',
  'Soprano',
  'Jean‐Louis Aubert',
  'Téléphone',
  'Olivia Ruiz',
  'Oxmo Puccino',
  'Tété',
  'Rohff',
  'Akhenaton',
  'Clara Luciani',
  'Grand Corps Malade',
  'Cali',
  'Kery James',
  'Shaka Ponk',
  'Bigflo & Oli',
  'Stupeflip',
  'Orelsan',
  'Camélia Jordana',
  'The Dø',
  'Priscilla',
  'Desireless',
  'Youssoupha',
  'PNL',
  'Bénabar',
  'Tal',
  'Keny Arkana',
  'Diam’s',
  'Kendji Girac',
  'Disiz',
  'Chantal Goya',
  'Dionysos',
  'Slimane',
  'Les Wampas',
  'Vald',
  'Les Fatals Picards',
  'Chinese Man',
  'Sanseverino',
  'Vianney',
  'Birdy Nam Nam',
  'Tryo',
  'Miossec',
  'Louis Chédid',
  'Kaaris',
  'Patrick Sébastien',
  'Arthur H',
  'Francky Vincent',
  'Julie Zenatti',
  'Manau',
  'Black M',
  'Doc Gynéco',
  'Matmatah',
  'Richard Gotainer',
  'Indila',
  'Zebda',
  'Barbara Pravi',
  'Vincent Delerm',
  'Rilès',
  'La Compagnie Créole',
  'SCH',
  'Thomas Bangalter',
  'Polo & Pan',
  'Dany Brillant',
  'Christophe Willem',
  'Céline Dion',
  'Lara Fabian',
  'Garou',
  'Natasha St-Pier',
  'Les Trois Accords',
  'Angèle',
  'Stromae',
  'Nekfeu',
  'Gazo',
  'Zaho de Sagazan',
  'Claudio Capéo',
  'Mika',
  'Louis Bertignac',
  'Émile et Images',
  'Thomas Dutronc',
  'Cœur de pirate',
  'Kyo',
  'Roch Voisine',
  'Gilbert Montagné',
  'David Hallyday',
  'Axelle Red',
  'Catherine Ringer',
  'Gérald de Palmas',
  'Isabelle Boulay',
  'Hoshi',
  'Tina Arena',
  'Eddy de Pretto',
  'Gaëtan Roussel',
  'Jérémy Frérot',
  'Santa',
  'Juliette Armanet',
  'Dave',
  'Pierre Garnier',
  'Axel Bauer',
  'Stephan Eicher',
  'Emmanuel Moire',
  'Zaho',
  'Mickey 3D',
  'Renan Luce',
  'Nana Mouskouri',
  'Corneille',
  'C2C',
  '2be3',
]

const MUSIC_ARTISTS_INTL_WORDS = [
  'The Beatles',
  'The Rolling Stones',
  'Bob Dylan',
  'David Bowie',
  'Led Zeppelin',
  'Bruce Springsteen',
  'Prince',
  'The Who',
  'Elvis Presley',
  'Jimi Hendrix',
  'The Beach Boys',
  'Shakira',
  'R.E.M.',
  'The Velvet Underground',
  'Marvin Gaye',
  'U2',
  'The Clash',
  'Nirvana',
  'Bruno Mars',
  'Radiohead',
  'Neil Young',
  'Stevie Wonder',
  'Pink',
  'Pink Floyd',
  'Jennifer Lopez',
  'Bob Marley and The Wailers',
  'Aretha Franklin',
  'Public Enemy',
  'Harry Styles',
  'Rosalía',
  'The Doors',
  'Miles Davis',
  'James Brown',
  'The Kinks',
  'Beastie Boys',
  'Creedence Clearwater Revival',
  'Otis Redding',
  'Michael Jackson',
  'Beck',
  'Sex Pistols',
  'Johnny Cash',
  'John Lennon',
  'Pixies',
  'Blur',
  'Ramones',
  'Madonna',
  'Lou Reed',
  'Sonic Youth',
  'Simon and Garfunkel',
  'Joy Division',
  'Oasis',
  'OutKast',
  'Dido',
  'Ray Charles',
  'The Police',
  'PJ Harvey',
  'Björk',
  'Massive Attack',
  'Chuck Berry',
  'The White Stripes',
  'Eminem',
  'Frank Sinatra',
  'The Cure',
  'AC/DC',
  'Metallica',
  'Black Sabbath',
  'Fleetwood Mac',
  'Guns \'n\' Roses',
  'Nick Cave',
  'Missy Elliott',
  'Patti Smith',
  'The Eagles',
  'Paul Simon',
  'Elton John',
  'Run-D.M.C.',
  'Blondie',
  'Leonard Cohen',
  'Franz Ferdinand',
  'The Smashing Pumpkins',
  'Aerosmith',
  'Duke Ellington',
  'Queen',
  'The Strokes',
  'The Chemical Brothers',
  'Kate Bush',
  'Kanye West',
  'Deep Purple',
  'Jay-Z',
  'Janis Joplin',
  'Coldplay',
  'Red Hot Chili Peppers',
  'Santana',
  'Dr. Dre',
  'Depeche Mode',
  'David Guetta',
  'Ella Fitzgerald',
  'Jerry Lee Lewis',
  'Nine Inch Nails',
  'Portishead',
  'The Prodigy',
  'Queens of the Stone Age',
  'The Bee Gees',
  'Iggy Pop',
  'Daft Punk',
  'Notorious B.I.G.',
  'Jimmy Cliff',
  'ABBA',
  'One Direction',
  'Dire Straits',
  'Sinead O\'Connor',
  'TLC',
  'Green Day',
  'Aphex Twin',
  'Die Antwoord',
  'Fugazi',
  'Avicii',
  'Gorillaz',
  'Rage Against the Machine',
  'Lauryn Hill',
  'Fatboy Slim',
  'Eric Clapton',
  'Offspring',
  'Alt-J',
  'Limp Bizkit',
  'DJ Shadow',
  'B.B. King',
  'Genesis',
  'Jeff Buckley',
  'Paul McCartney',
  'Fugees',
  'Sigur Ros',
  'M.I.A.',
  'The Jackson 5',
  'Wu-Tang Clan',
  'Air',
  'The Animals',
  'DJ Snake',
  'The Arcade Fire',
  'Adele',
  'Kiss',
  'Snoop Doggy Dogg',
  'Imagine Dragons',
  'Louis Armstrong',
  'Moby',
  'The Roots',
  'Cypress Hill',
  'Cyndi Lauper',
  'Serge Gainsbourg',
  'Janet Jackson',
  'Tracy Chapman',
  'George Michael',
  'Alanis Morissette',
  'Eurythmics',
  'The Mamas and the Papas',
  'Joe Cocker',
  'Arctic Monkeys',
  'Dolly Parton',
  'The Shins',
  'Foo Fighters',
  '2Pac',
  'Bloc Party',
  'ZZ Top',
  'System of a Down',
  'Bon Jovi',
  'Archive',
  'Iron Maiden',
  'Etta James',
  'Bright Eyes',
  'Tina Turner',
  'Bon Iver',
  '50 Cent',
  'Britney Spears',
  'Mary J. Blige',
  'Jeff Beck',
  'Nas',
  'Beyonce',
  'Cat Stevens',
  'Devendra Banhart',
  'Manu Chao',
  'Drake',
  'Kylie Minogue',
  'Blink 182',
  'Sum 41',
  'Godspeed You Black Emperor!',
  'Aaliyah',
  'Eels',
  'Maroon 5',
  'Buena Vista Social Club',
  'The Killers',
  'Alicia Keys',
  'Gnarls Barkley',
  'Justin Timberlake',
  'Lenny Kravitz',
  'R. Kelly',
  'Placebo',
  'Black Eyes Peas',
  'Nina Simone',
  'Mobb Deep',
  'Norah Jones',
  'Supertramp',
  'Sting',
  'Youssou N\'Dour',
  'Shania Twain',
  'Barbra Streisand',
  'Korn',
  'Phil Collins',
  'Gwen Stefani',
  'Marilyn Manson',
  'Justin Bieber',
  'Journey',
  'Nancy Sinatra',
  'Twenty One Pilots',
  'Lana Del Rey',
  'Usher',
  'Muse',
  'M83',
  'Joan Baez',
  'Backstreet Boys',
  'Lionel Richie',
  'Chris Isaak',
  'Ice-T',
  'Pharrell Williams',
  'No Doubt',
  'Spice Girls',
  'Death in Vegas',
  'Kendrick Lamar',
  'Selena Gomez',
  'The Weeknd',
  'Miley Cyrus',
  'Lady Gaga',
  'Ariana Grande',
  'Taylor Swift',
  'Bad Bunny',
  'Ed Sheeran',
  'Linkin Park',
  'Travis Scott',
  'Sabrina Carpenter',
  'Tyler, the Creator',
  'Katy Perry',
  'Nicki Minaj',
  'The Cranberries',
  'Mariah Carey',
  'Nickelback',
  'Frank Ocean',
  'Lorde',
  'Rihanna',
  'James Blake',
  'Charli XCX',
  'Billie Eilish',
  'Childish Gambino',
  'Sia',
  'Major Lazer',
]

async function ensureWordCategory(
  em: EntityManager,
  slug: string,
  name: string,
): Promise<WordCategory> {
  const existing = await em.findOne(WordCategory, { slug })
  if (existing)
    return existing

  const category = new WordCategory()
  category.slug = slug
  category.name = name
  await em.persistAndFlush(category)
  return category
}

async function seedWordsForCategoryIfEmpty(
  em: EntityManager,
  category: WordCategory,
  labels: readonly string[],
): Promise<void> {
  const count = await em.count(Word, { category })
  if (count > 0)
    return

  const words = labels.map((label) => {
    const word = new Word()
    word.label = label
    word.category = category
    return word
  })

  await em.persistAndFlush(words)
}

export class WordsSeeder extends Seeder {
  async run(em: EntityManager): Promise<void> {
    const baseCategory = await ensureWordCategory(
      em,
      WORD_CATEGORY_SLUG.BASE,
      'Mots de base',
    )
    const frCategory = await ensureWordCategory(
      em,
      WORD_CATEGORY_SLUG.MUSIC_ARTISTS_FR,
      'Artistes musicaux francophones',
    )
    const intlCategory = await ensureWordCategory(
      em,
      WORD_CATEGORY_SLUG.MUSIC_ARTISTS_INTL,
      'Artistes musicaux internationaux',
    )

    await seedWordsForCategoryIfEmpty(em, baseCategory, BASE_WORDS)
    await seedWordsForCategoryIfEmpty(em, frCategory, MUSIC_ARTISTS_FR_WORDS)
    await seedWordsForCategoryIfEmpty(em, intlCategory, MUSIC_ARTISTS_INTL_WORDS)
  }
}
