// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  AppControllerGetHelloData,
  AppControllerGetHelloResponses,
  GamesControllerGetGamesData,
  GamesControllerGetGamesResponses,
  GamesControllerCreateGameData,
  GamesControllerCreateGameResponses,
  GamesControllerGetGameData,
  GamesControllerGetGameResponses,
  GamesControllerGetGameStateData,
  GamesControllerGetGameStateResponses,
  GamesControllerJoinGameData,
  GamesControllerJoinGameResponses,
  GamesControllerKickPlayerData,
  GamesControllerKickPlayerResponses,
  GamesControllerLeaveGameData,
  GamesControllerLeaveGameResponses,
  GamesControllerChooseSideData,
  GamesControllerChooseSideResponses,
  GamesControllerDesignateSpyData,
  GamesControllerDesignateSpyResponses,
  GamesControllerStartRoundData,
  GamesControllerStartRoundResponses,
  GamesControllerGiveClueData,
  GamesControllerGiveClueResponses,
  GamesControllerSelectWordData,
  GamesControllerSelectWordResponses,
  GamesControllerHighlightWordData,
  GamesControllerHighlightWordResponses,
  GamesControllerUnhighlightWordData,
  GamesControllerUnhighlightWordResponses,
  GamesControllerPassTurnData,
  GamesControllerPassTurnResponses,
  GamesControllerRestartGameData,
  GamesControllerRestartGameResponses,
  WordsControllerGetRandomWordsData,
  WordsControllerGetRandomWordsResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const appControllerGetHello = <ThrowOnError extends boolean = false>(
  options?: Options<AppControllerGetHelloData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    AppControllerGetHelloResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api",
    ...options,
  });
};

export const gamesControllerGetGames = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerGetGamesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GamesControllerGetGamesResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games",
    ...options,
  });
};

export const gamesControllerCreateGame = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerCreateGameData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerCreateGameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerGetGame = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerGetGameData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GamesControllerGetGameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}",
    ...options,
  });
};

export const gamesControllerGetGameState = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GamesControllerGetGameStateData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GamesControllerGetGameStateResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/state",
    ...options,
  });
};

export const gamesControllerJoinGame = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerJoinGameData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerJoinGameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/join",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerKickPlayer = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerKickPlayerData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    GamesControllerKickPlayerResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/players/{playerId}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerLeaveGame = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerLeaveGameData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    GamesControllerLeaveGameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/leave",
    ...options,
  });
};

export const gamesControllerChooseSide = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerChooseSideData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    GamesControllerChooseSideResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/players/me/side",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerDesignateSpy = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GamesControllerDesignateSpyData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    GamesControllerDesignateSpyResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/players/me/spy",
    ...options,
  });
};

export const gamesControllerStartRound = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerStartRoundData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerStartRoundResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/rounds/start",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerGiveClue = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerGiveClueData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerGiveClueResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/rounds/current/clue",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerSelectWord = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerSelectWordData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerSelectWordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/rounds/current/select",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerHighlightWord = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GamesControllerHighlightWordData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerHighlightWordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/rounds/current/highlight",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

export const gamesControllerUnhighlightWord = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GamesControllerUnhighlightWordData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    GamesControllerUnhighlightWordResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/rounds/current/highlight/{wordIndex}",
    ...options,
  });
};

export const gamesControllerPassTurn = <ThrowOnError extends boolean = false>(
  options: Options<GamesControllerPassTurnData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerPassTurnResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/rounds/current/pass",
    ...options,
  });
};

export const gamesControllerRestartGame = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GamesControllerRestartGameData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    GamesControllerRestartGameResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/games/{id}/restart",
    ...options,
  });
};

export const wordsControllerGetRandomWords = <
  ThrowOnError extends boolean = false,
>(
  options: Options<WordsControllerGetRandomWordsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    WordsControllerGetRandomWordsResponses,
    unknown,
    ThrowOnError
  >({
    url: "/api/words/random",
    ...options,
  });
};
