// This file is auto-generated by @hey-api/openapi-ts

/**
 * CreateGameSchema
 * Schema for creating a game
 */
export type CreateGameSchema = {
  pseudo: string;
};

/**
 * JoinGameSchema
 * Schema for joining a game
 */
export type JoinGameSchema = {
  pseudo: string;
};

/**
 * KickPlayerSchema
 * Schema for kicking a player (creator only)
 */
export type KickPlayerSchema = {
  creatorToken: string;
};

/**
 * ChooseSideSchema
 * Schema for choosing team side
 */
export type ChooseSideSchema = {
  side: SideSchema;
};

/**
 * AssignPlayerSideByCreatorSchema
 * Schema for the host to assign a waiting player to a team during an active round
 */
export type AssignPlayerSideByCreatorSchema = {
  side: SideSchema;
  creatorToken: string;
};

/**
 * DesignatePlayerAsSpySchema
 * Schema for creator to designate a player as spy
 */
export type DesignatePlayerAsSpySchema = {
  creatorToken: string;
};

/**
 * SetTimerSettingsSchema
 * Lobby timer settings (host only)
 */
export type SetTimerSettingsSchema = {
  creatorToken: string;
  isEnabled: boolean;
  durationSeconds: number;
};

/**
 * StartRoundSchema
 * Schema for starting a round
 */
export type StartRoundSchema = {
  wordCount?: number;
  timerSettings?: {
    creatorToken: string;
    isEnabled: boolean;
    durationSeconds: number;
  };
};

/**
 * GiveClueSchema
 * Schema for giving a clue
 */
export type GiveClueSchema = {
  word: string;
  number: number;
};

/**
 * SelectWordSchema
 * Schema for selecting a word
 */
export type SelectWordSchema = {
  wordIndex: number;
};

/**
 * HighlightWordSchema
 * Schema for highlighting a word
 */
export type HighlightWordSchema = {
  wordIndex: number;
};

/**
 * SendChatSchema
 * Schema for sending a chat message
 */
export type SendChatSchema = {
  content: string;
};

/**
 * WordsSchema
 * Schema for a list of words
 */
export type WordsSchema = Array<WordSchema>;

/**
 * WordSchema
 * Schema for a word
 */
export type WordSchema = {
  id: string;
  label: string;
};

/**
 * AdminOngoingGameSchema
 * Game row for admin spectator listing
 */
export type AdminOngoingGameSchema = {
  id: string;
  status: "LOBBY" | "PLAYING" | "FINISHED";
  creatorPseudo: string;
  createdAt: string;
};

export type GetAdminOngoing = Array<AdminOngoingGameSchema>;

/**
 * AdminWatchResponseSchema
 * Spectator session id (X-Player-Id) for admin watch mode
 */
export type AdminWatchResponseSchema = {
  playerId: string;
};

/**
 * AdminUnwatchOkSchema
 * Admin spectator session ended
 */
export type AdminUnwatchOkSchema = {
  ok: true;
};

/**
 * CreateGameResponseSchema
 * Response when creating a game
 */
export type CreateGameResponseSchema = {
  game: GameSchema;
  creatorToken: string;
  playerId: string;
  gameState: GameStateSchema;
};

/**
 * GameSchema
 * Schema for a game (basic info)
 */
export type GameSchema = {
  id: string;
  creatorPseudo: string;
  createdAt: string;
};

/**
 * GameStateSchema
 * Full game state computed from events
 */
export type GameStateSchema = {
  status: "LOBBY" | "PLAYING" | "FINISHED";
  players: Array<GameStatePlayerSchema>;
  currentRound: {
    id: string;
    words: Array<string>;
    results?: Array<"neutral" | "red" | "blue" | "black">;
    order: number;
    /**
     * SideSchema
     * Player side in a game
     */
    currentTurn: "red" | "blue";
    currentClue: {
      word: string;
      number: number;
    } | null;
    guessesRemaining: number;
    revealedWords: Array<{
      wordIndex: number;
      /**
       * CardTypeSchema
       * Card type in the grid
       */
      cardType: "neutral" | "red" | "blue" | "black";
    }>;
    /**
     * Total red/blue team cards on the grid (target per team)
     */
    wordsTotalBySide: {
      red: number;
      blue: number;
    };
    /**
     * Unrevealed red/blue card counts for each team (all players; full grid only for spies)
     */
    wordsRemainingBySide: {
      red: number;
      blue: number;
    };
    highlights: {
      [key: string]: Array<{
        playerId: string;
        playerName: string;
      }>;
    };
    turnStartedAt?: string | null;
  } | null;
  winningSide: ("red" | "blue") | null;
  losingSide: ("red" | "blue") | null;
  timerSettings?: {
    isEnabled: boolean;
    durationSeconds: number;
  } | null;
};

/**
 * GameStatePlayerSchema
 * Player in game state
 */
export type GameStatePlayerSchema = {
  id: string;
  name: string;
  side: ("red" | "blue") | null;
  isSpy?: boolean;
};

/**
 * JoinGameResponseSchema
 * Response when joining a game
 */
export type JoinGameResponseSchema = {
  gameState: GameStateSchema;
  playerId: string;
};

/**
 * TimelineResponseSchema
 * Paginated timeline response
 */
export type TimelineResponseSchema = {
  data: Array<TimelineItemSchema>;
  meta: {
    itemCount: number;
    pageSize: number;
    offset: number;
    hasMore: boolean;
  };
};

/**
 * TimelineItemSchema
 * Timeline item (event or chat message)
 */
export type TimelineItemSchema = {
  id: string;
  type: "event" | "chat";
  eventType?: string;
  payload: {
    [key: string]: unknown;
  };
  triggeredBy: string | null;
  playerName?: string;
  createdAt: string;
  roundId?: string | null;
};

/**
 * SideSchema
 * Player side in a game
 */
export const SideSchema = {
  RED: "red",
  BLUE: "blue",
} as const;

/**
 * SideSchema
 * Player side in a game
 */
export type SideSchema = (typeof SideSchema)[keyof typeof SideSchema];

/**
 * PaginationQuerySchema
 * Schema for pagination query
 */
export type PaginationQuerySchema = {
  /**
   * Starting position of the query
   */
  offset: number;
  /**
   * Number of items to return
   */
  pageSize: number;
};

export type AppControllerGetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api";
};

export type AppControllerGetHelloResponses = {
  200: unknown;
};

export type GamesControllerListAdminOngoingGamesData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/games/admin/ongoing";
};

export type GamesControllerListAdminOngoingGamesResponses = {
  /**
   * Successful response
   */
  200: GetAdminOngoing;
};

export type GamesControllerListAdminOngoingGamesResponse =
  GamesControllerListAdminOngoingGamesResponses[keyof GamesControllerListAdminOngoingGamesResponses];

export type GamesControllerAdminWatchGameData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/admin/watch";
};

export type GamesControllerAdminWatchGameResponses = {
  /**
   * Spectator session id (X-Player-Id) for admin watch mode
   */
  200: AdminWatchResponseSchema;
};

export type GamesControllerAdminWatchGameResponse =
  GamesControllerAdminWatchGameResponses[keyof GamesControllerAdminWatchGameResponses];

export type GamesControllerAdminUnwatchGameData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/admin/unwatch";
};

export type GamesControllerAdminUnwatchGameResponses = {
  /**
   * Admin spectator session ended
   */
  200: AdminUnwatchOkSchema;
};

export type GamesControllerAdminUnwatchGameResponse =
  GamesControllerAdminUnwatchGameResponses[keyof GamesControllerAdminUnwatchGameResponses];

export type GamesControllerCreateGameData = {
  /**
   * CreateGameSchema
   * Schema for creating a game
   */
  body: {
    pseudo: string;
  };
  path?: never;
  query?: never;
  url: "/api/games";
};

export type GamesControllerCreateGameResponses = {
  /**
   * Response when creating a game
   */
  200: CreateGameResponseSchema;
};

export type GamesControllerCreateGameResponse =
  GamesControllerCreateGameResponses[keyof GamesControllerCreateGameResponses];

export type GamesControllerGetGameStateData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/state";
};

export type GamesControllerGetGameStateResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerGetGameStateResponse =
  GamesControllerGetGameStateResponses[keyof GamesControllerGetGameStateResponses];

export type GamesControllerJoinGameData = {
  /**
   * JoinGameSchema
   * Schema for joining a game
   */
  body: {
    pseudo: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/join";
};

export type GamesControllerJoinGameResponses = {
  /**
   * Response when joining a game
   */
  200: JoinGameResponseSchema;
};

export type GamesControllerJoinGameResponse =
  GamesControllerJoinGameResponses[keyof GamesControllerJoinGameResponses];

export type GamesControllerKickPlayerData = {
  /**
   * KickPlayerSchema
   * Schema for kicking a player (creator only)
   */
  body: {
    creatorToken: string;
  };
  path: {
    playerId: string;
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/players/{playerId}";
};

export type GamesControllerKickPlayerResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerKickPlayerResponse =
  GamesControllerKickPlayerResponses[keyof GamesControllerKickPlayerResponses];

export type GamesControllerLeaveGameData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/leave";
};

export type GamesControllerLeaveGameResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerLeaveGameResponse =
  GamesControllerLeaveGameResponses[keyof GamesControllerLeaveGameResponses];

export type GamesControllerChooseSideData = {
  /**
   * ChooseSideSchema
   * Schema for choosing team side
   */
  body: {
    /**
     * SideSchema
     * Player side in a game
     */
    side: "red" | "blue";
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/players/me/side";
};

export type GamesControllerChooseSideResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerChooseSideResponse =
  GamesControllerChooseSideResponses[keyof GamesControllerChooseSideResponses];

export type GamesControllerAssignPlayerSideByCreatorData = {
  /**
   * AssignPlayerSideByCreatorSchema
   * Schema for the host to assign a waiting player to a team during an active round
   */
  body: {
    /**
     * SideSchema
     * Player side in a game
     */
    side: "red" | "blue";
    creatorToken: string;
  };
  path: {
    playerId: string;
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/creator/players/{playerId}/side";
};

export type GamesControllerAssignPlayerSideByCreatorResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerAssignPlayerSideByCreatorResponse =
  GamesControllerAssignPlayerSideByCreatorResponses[keyof GamesControllerAssignPlayerSideByCreatorResponses];

export type GamesControllerDesignateSpyData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/players/me/spy";
};

export type GamesControllerDesignateSpyResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerDesignateSpyResponse =
  GamesControllerDesignateSpyResponses[keyof GamesControllerDesignateSpyResponses];

export type GamesControllerDesignatePlayerAsSpyData = {
  /**
   * DesignatePlayerAsSpySchema
   * Schema for creator to designate a player as spy
   */
  body: {
    creatorToken: string;
  };
  path: {
    playerId: string;
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/players/{playerId}/spy";
};

export type GamesControllerDesignatePlayerAsSpyResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerDesignatePlayerAsSpyResponse =
  GamesControllerDesignatePlayerAsSpyResponses[keyof GamesControllerDesignatePlayerAsSpyResponses];

export type GamesControllerSetTimerSettingsData = {
  /**
   * SetTimerSettingsSchema
   * Lobby timer settings (host only)
   */
  body: {
    creatorToken: string;
    isEnabled: boolean;
    durationSeconds: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/timer-settings";
};

export type GamesControllerSetTimerSettingsResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerSetTimerSettingsResponse =
  GamesControllerSetTimerSettingsResponses[keyof GamesControllerSetTimerSettingsResponses];

export type GamesControllerStartRoundData = {
  /**
   * StartRoundSchema
   * Schema for starting a round
   */
  body: {
    wordCount?: number;
    timerSettings?: {
      creatorToken: string;
      isEnabled: boolean;
      durationSeconds: number;
    };
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/rounds/start";
};

export type GamesControllerStartRoundResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerStartRoundResponse =
  GamesControllerStartRoundResponses[keyof GamesControllerStartRoundResponses];

export type GamesControllerGiveClueData = {
  /**
   * GiveClueSchema
   * Schema for giving a clue
   */
  body: {
    word: string;
    number: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/rounds/current/clue";
};

export type GamesControllerGiveClueResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerGiveClueResponse =
  GamesControllerGiveClueResponses[keyof GamesControllerGiveClueResponses];

export type GamesControllerSelectWordData = {
  /**
   * SelectWordSchema
   * Schema for selecting a word
   */
  body: {
    wordIndex: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/rounds/current/select";
};

export type GamesControllerSelectWordResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerSelectWordResponse =
  GamesControllerSelectWordResponses[keyof GamesControllerSelectWordResponses];

export type GamesControllerHighlightWordData = {
  /**
   * HighlightWordSchema
   * Schema for highlighting a word
   */
  body: {
    wordIndex: number;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/rounds/current/highlight";
};

export type GamesControllerHighlightWordResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerHighlightWordResponse =
  GamesControllerHighlightWordResponses[keyof GamesControllerHighlightWordResponses];

export type GamesControllerUnhighlightWordData = {
  body?: never;
  path: {
    wordIndex: number;
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/rounds/current/highlight/{wordIndex}";
};

export type GamesControllerUnhighlightWordResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerUnhighlightWordResponse =
  GamesControllerUnhighlightWordResponses[keyof GamesControllerUnhighlightWordResponses];

export type GamesControllerPassTurnData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/rounds/current/pass";
};

export type GamesControllerPassTurnResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerPassTurnResponse =
  GamesControllerPassTurnResponses[keyof GamesControllerPassTurnResponses];

export type GamesControllerRestartGameData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/restart";
};

export type GamesControllerRestartGameResponses = {
  /**
   * Full game state computed from events
   */
  200: GameStateSchema;
};

export type GamesControllerRestartGameResponse =
  GamesControllerRestartGameResponses[keyof GamesControllerRestartGameResponses];

export type GamesControllerSendChatData = {
  /**
   * SendChatSchema
   * Schema for sending a chat message
   */
  body: {
    content: string;
  };
  path: {
    id: string;
  };
  query?: never;
  url: "/api/games/{id}/chat";
};

export type GamesControllerSendChatResponses = {
  201: unknown;
};

export type GamesControllerGetTimelineData = {
  body?: never;
  path: {
    id: string;
  };
  query: {
    roundId: string;
    /**
     * Starting position of the query
     */
    offset: number;
    /**
     * Number of items to return
     */
    pageSize: number;
  };
  url: "/api/games/{id}/timeline";
};

export type GamesControllerGetTimelineResponses = {
  /**
   * Paginated timeline response
   */
  200: TimelineResponseSchema;
};

export type GamesControllerGetTimelineResponse =
  GamesControllerGetTimelineResponses[keyof GamesControllerGetTimelineResponses];

export type WordsControllerGetRandomWordsData = {
  body?: never;
  path?: never;
  query: {
    count: string;
  };
  url: "/api/words/random";
};

export type WordsControllerGetRandomWordsResponses = {
  /**
   * Schema for a list of words
   */
  200: WordsSchema;
};

export type WordsControllerGetRandomWordsResponse =
  WordsControllerGetRandomWordsResponses[keyof WordsControllerGetRandomWordsResponses];

export type ClientOptions = {
  baseUrl: string;
};
