// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * CreateGameSchema
 * Schema for creating a game
 */
export const zCreateGameSchema = z.object({
  pseudo: z.string().min(1).max(100),
});

/**
 * JoinGameSchema
 * Schema for joining a game
 */
export const zJoinGameSchema = z.object({
  pseudo: z.string().min(1).max(100),
});

/**
 * KickPlayerSchema
 * Schema for kicking a player (creator only)
 */
export const zKickPlayerSchema = z.object({
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * SideSchema
 * Player side in a game
 */
export const zSideSchema = z.enum(["red", "blue"]);

/**
 * ChooseSideSchema
 * Schema for choosing team side
 */
export const zChooseSideSchema = z.object({
  side: zSideSchema,
});

/**
 * AssignPlayerSideByCreatorSchema
 * Schema for the host to assign a waiting player to a team during an active round
 */
export const zAssignPlayerSideByCreatorSchema = z.object({
  side: zSideSchema,
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * ShuffleLobbyTeamsSchema
 * Schema for the host to randomly redistribute players across teams in the lobby
 */
export const zShuffleLobbyTeamsSchema = z.object({
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * DesignatePlayerAsSpySchema
 * Schema for creator to designate a player as spy
 */
export const zDesignatePlayerAsSpySchema = z.object({
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * SetTimerSettingsSchema
 * Lobby timer settings (host only)
 */
export const zSetTimerSettingsSchema = z.object({
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  isEnabled: z.boolean(),
  durationSeconds: z.int().gte(60).lte(3600),
});

/**
 * StartRoundSchema
 * Schema for starting a round
 */
export const zStartRoundSchema = z.object({
  wordCount: z.optional(z.int().gte(1).lte(400)),
  timerSettings: z.optional(
    z.object({
      creatorToken: z
        .uuid()
        .regex(
          /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
        ),
      isEnabled: z.boolean(),
      durationSeconds: z.int().gte(60).lte(3600),
    }),
  ),
});

/**
 * GiveClueSchema
 * Schema for giving a clue
 */
export const zGiveClueSchema = z.object({
  word: z.string().min(1),
  number: z.int().gte(0).lte(9007199254740991),
});

/**
 * SelectWordSchema
 * Schema for selecting a word
 */
export const zSelectWordSchema = z.object({
  wordIndex: z.int().gte(0).lte(9007199254740991),
});

/**
 * HighlightWordSchema
 * Schema for highlighting a word
 */
export const zHighlightWordSchema = z.object({
  wordIndex: z.int().gte(0).lte(9007199254740991),
});

/**
 * SendChatSchema
 * Schema for sending a chat message
 */
export const zSendChatSchema = z.object({
  content: z.string().min(1).max(500),
});

/**
 * WordSchema
 * Schema for a word
 */
export const zWordSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  label: z.string(),
});

/**
 * WordsSchema
 * Schema for a list of words
 */
export const zWordsSchema = z.array(zWordSchema);

/**
 * AdminOngoingGameSchema
 * Game row for admin spectator listing
 */
export const zAdminOngoingGameSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  status: z.enum(["LOBBY", "PLAYING", "FINISHED"]),
  creatorPseudo: z.string(),
  createdAt: z.string(),
});

export const zGetAdminOngoing = z.array(zAdminOngoingGameSchema);

/**
 * AdminWatchResponseSchema
 * Spectator session id (X-Player-Id) for admin watch mode
 */
export const zAdminWatchResponseSchema = z.object({
  playerId: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * AdminUnwatchOkSchema
 * Admin spectator session ended
 */
export const zAdminUnwatchOkSchema = z.object({
  ok: z.literal(true),
});

/**
 * GameSchema
 * Schema for a game (basic info)
 */
export const zGameSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  creatorPseudo: z.string(),
  createdAt: z.string(),
});

/**
 * GameStatePlayerSchema
 * Player in game state
 */
export const zGameStatePlayerSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  name: z.string(),
  side: z.union([z.enum(["red", "blue"]), z.null()]),
  isSpy: z.optional(z.boolean()),
});

/**
 * GameStateSchema
 * Full game state computed from events
 */
export const zGameStateSchema = z.object({
  status: z.enum(["LOBBY", "PLAYING", "FINISHED"]),
  players: z.array(zGameStatePlayerSchema),
  currentRound: z.union([
    z.object({
      id: z
        .uuid()
        .regex(
          /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
        ),
      words: z.array(z.string()),
      results: z.optional(z.array(z.enum(["neutral", "red", "blue", "black"]))),
      order: z.int().gt(0).lte(9007199254740991),
      currentTurn: z.enum(["red", "blue"]),
      currentClue: z.union([
        z.object({
          word: z.string(),
          number: z.int().gte(0).lte(9007199254740991),
        }),
        z.null(),
      ]),
      guessesRemaining: z.int().gte(0).lte(9007199254740991),
      revealedWords: z.array(
        z.object({
          wordIndex: z.int().gte(0).lte(9007199254740991),
          cardType: z.enum(["neutral", "red", "blue", "black"]),
        }),
      ),
      wordsTotalBySide: z.object({
        red: z.int().gte(0).lte(9007199254740991),
        blue: z.int().gte(0).lte(9007199254740991),
      }),
      wordsRemainingBySide: z.object({
        red: z.int().gte(0).lte(9007199254740991),
        blue: z.int().gte(0).lte(9007199254740991),
      }),
      highlights: z.record(
        z.string(),
        z.array(
          z.object({
            playerId: z
              .uuid()
              .regex(
                /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
              ),
            playerName: z.string(),
          }),
        ),
      ),
      turnStartedAt: z.optional(z.union([z.string(), z.null()])),
    }),
    z.null(),
  ]),
  winningSide: z.union([z.enum(["red", "blue"]), z.null()]),
  losingSide: z.union([z.enum(["red", "blue"]), z.null()]),
  timerSettings: z.optional(
    z.union([
      z.object({
        isEnabled: z.boolean(),
        durationSeconds: z.int().gte(60).lte(3600),
      }),
      z.null(),
    ]),
  ),
});

/**
 * CreateGameResponseSchema
 * Response when creating a game
 */
export const zCreateGameResponseSchema = z.object({
  game: zGameSchema,
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  playerId: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  gameState: zGameStateSchema,
});

/**
 * JoinGameResponseSchema
 * Response when joining a game
 */
export const zJoinGameResponseSchema = z.object({
  gameState: zGameStateSchema,
  playerId: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * TimelineItemSchema
 * Timeline item (event or chat message)
 */
export const zTimelineItemSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  type: z.enum(["event", "chat"]),
  eventType: z.optional(z.string()),
  payload: z.record(z.string(), z.unknown()),
  triggeredBy: z.union([
    z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    z.null(),
  ]),
  playerName: z.optional(z.string()),
  createdAt: z.string(),
  roundId: z.optional(
    z.union([
      z
        .uuid()
        .regex(
          /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
        ),
      z.null(),
    ]),
  ),
});

/**
 * TimelineResponseSchema
 * Paginated timeline response
 */
export const zTimelineResponseSchema = z.object({
  data: z.array(zTimelineItemSchema),
  meta: z.object({
    itemCount: z.number(),
    pageSize: z.number(),
    offset: z.number(),
    hasMore: z.boolean(),
  }),
});

/**
 * PaginationQuerySchema
 * Schema for pagination query
 */
export const zPaginationQuerySchema = z.object({
  offset: z.int().gte(0).lte(9007199254740991).default(0),
  pageSize: z.int().gte(1).lte(100).default(20),
});

export const zAppControllerGetHelloData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGamesControllerListAdminOngoingGamesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful response
 */
export const zGamesControllerListAdminOngoingGamesResponse = zGetAdminOngoing;

export const zGamesControllerAdminWatchGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Spectator session id (X-Player-Id) for admin watch mode
 */
export const zGamesControllerAdminWatchGameResponse = zAdminWatchResponseSchema;

export const zGamesControllerAdminUnwatchGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Admin spectator session ended
 */
export const zGamesControllerAdminUnwatchGameResponse = zAdminUnwatchOkSchema;

export const zGamesControllerCreateGameData = z.object({
  body: z.object({
    pseudo: z.string().min(1).max(100),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response when creating a game
 */
export const zGamesControllerCreateGameResponse = zCreateGameResponseSchema;

export const zGamesControllerGetGameStateData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerGetGameStateResponse = zGameStateSchema;

export const zGamesControllerJoinGameData = z.object({
  body: z.object({
    pseudo: z.string().min(1).max(100),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Response when joining a game
 */
export const zGamesControllerJoinGameResponse = zJoinGameResponseSchema;

export const zGamesControllerKickPlayerData = z.object({
  body: z.object({
    creatorToken: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  path: z.object({
    playerId: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerKickPlayerResponse = zGameStateSchema;

export const zGamesControllerLeaveGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerLeaveGameResponse = zGameStateSchema;

export const zGamesControllerChooseSideData = z.object({
  body: z.object({
    side: z.enum(["red", "blue"]),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerChooseSideResponse = zGameStateSchema;

export const zGamesControllerAssignPlayerSideByCreatorData = z.object({
  body: z.object({
    side: z.enum(["red", "blue"]),
    creatorToken: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  path: z.object({
    playerId: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerAssignPlayerSideByCreatorResponse =
  zGameStateSchema;

export const zGamesControllerShuffleLobbyTeamsData = z.object({
  body: z.object({
    creatorToken: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerShuffleLobbyTeamsResponse = zGameStateSchema;

export const zGamesControllerDesignateSpyData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerDesignateSpyResponse = zGameStateSchema;

export const zGamesControllerDesignatePlayerAsSpyData = z.object({
  body: z.object({
    creatorToken: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  path: z.object({
    playerId: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerDesignatePlayerAsSpyResponse = zGameStateSchema;

export const zGamesControllerSetTimerSettingsData = z.object({
  body: z.object({
    creatorToken: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    isEnabled: z.boolean(),
    durationSeconds: z.int().gte(60).lte(3600),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerSetTimerSettingsResponse = zGameStateSchema;

export const zGamesControllerStartRoundData = z.object({
  body: z.object({
    wordCount: z.optional(z.int().gte(1).lte(400)),
    timerSettings: z.optional(
      z.object({
        creatorToken: z
          .uuid()
          .regex(
            /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
          ),
        isEnabled: z.boolean(),
        durationSeconds: z.int().gte(60).lte(3600),
      }),
    ),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerStartRoundResponse = zGameStateSchema;

export const zGamesControllerGiveClueData = z.object({
  body: z.object({
    word: z.string().min(1),
    number: z.int().gte(0).lte(9007199254740991),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerGiveClueResponse = zGameStateSchema;

export const zGamesControllerSelectWordData = z.object({
  body: z.object({
    wordIndex: z.int().gte(0).lte(9007199254740991),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerSelectWordResponse = zGameStateSchema;

export const zGamesControllerHighlightWordData = z.object({
  body: z.object({
    wordIndex: z.int().gte(0).lte(9007199254740991),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerHighlightWordResponse = zGameStateSchema;

export const zGamesControllerUnhighlightWordData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    wordIndex: z.int().gte(0).lte(9007199254740991),
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerUnhighlightWordResponse = zGameStateSchema;

export const zGamesControllerPassTurnData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerPassTurnResponse = zGameStateSchema;

export const zGamesControllerRestartGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerRestartGameResponse = zGameStateSchema;

export const zGamesControllerSendChatData = z.object({
  body: z.object({
    content: z.string().min(1).max(500),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

export const zGamesControllerGetTimelineData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.object({
    roundId: z.string(),
    offset: z.int().gte(0).lte(9007199254740991).default(0),
    pageSize: z.int().gte(1).lte(100).default(20),
  }),
});

/**
 * Paginated timeline response
 */
export const zGamesControllerGetTimelineResponse = zTimelineResponseSchema;

export const zWordsControllerGetRandomWordsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    count: z.string(),
  }),
});

/**
 * Schema for a list of words
 */
export const zWordsControllerGetRandomWordsResponse = zWordsSchema;
