// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * CreateGameSchema
 * Schema for creating a game
 */
export const zCreateGameSchema = z.object({
  pseudo: z.string().min(1).max(100),
});

/**
 * JoinGameSchema
 * Schema for joining a game
 */
export const zJoinGameSchema = z.object({
  pseudo: z.string().min(1).max(100),
});

/**
 * KickPlayerSchema
 * Schema for kicking a player (creator only)
 */
export const zKickPlayerSchema = z.object({
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * SideSchema
 * Player side in a game
 */
export const zSideSchema = z.enum(["red", "blue"]);

/**
 * ChooseSideSchema
 * Schema for choosing team side
 */
export const zChooseSideSchema = z.object({
  side: zSideSchema,
});

/**
 * StartRoundSchema
 * Schema for starting a round
 */
export const zStartRoundSchema = z.object({
  wordCount: z.optional(z.int().gte(1).lte(400)),
});

/**
 * GiveClueSchema
 * Schema for giving a clue
 */
export const zGiveClueSchema = z.object({
  word: z.string().min(1),
  number: z.int().gte(0).lte(9007199254740991),
});

/**
 * SelectWordSchema
 * Schema for selecting a word
 */
export const zSelectWordSchema = z.object({
  wordIndex: z.int().gte(0).lte(9007199254740991),
});

/**
 * HighlightWordSchema
 * Schema for highlighting a word
 */
export const zHighlightWordSchema = z.object({
  wordIndex: z.int().gte(0).lte(9007199254740991),
});

/**
 * WordSchema
 * Schema for a word
 */
export const zWordSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  label: z.string(),
});

/**
 * WordsSchema
 * Schema for a list of words
 */
export const zWordsSchema = z.array(zWordSchema);

/**
 * GameSchema
 * Schema for a game (basic info)
 */
export const zGameSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  creatorPseudo: z.string(),
  createdAt: z.string(),
});

/**
 * GameStatePlayerSchema
 * Player in game state
 */
export const zGameStatePlayerSchema = z.object({
  id: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  name: z.string(),
  side: z.union([z.enum(["red", "blue"]), z.null()]),
  isSpy: z.optional(z.boolean()),
});

/**
 * GameStateSchema
 * Full game state computed from events
 */
export const zGameStateSchema = z.object({
  status: z.enum(["LOBBY", "PLAYING", "FINISHED"]),
  players: z.array(zGameStatePlayerSchema),
  currentRound: z.union([
    z.object({
      id: z
        .uuid()
        .regex(
          /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
        ),
      words: z.array(z.string()),
      results: z.array(z.enum(["neutral", "red", "blue", "black"])),
      order: z.int().gt(0).lte(9007199254740991),
      currentTurn: z.enum(["red", "blue"]),
      currentClue: z.union([
        z.object({
          word: z.string(),
          number: z.int().gte(0).lte(9007199254740991),
        }),
        z.null(),
      ]),
      guessesRemaining: z.int().gte(0).lte(9007199254740991),
      revealedWords: z.array(
        z.object({
          wordIndex: z.int().gte(0).lte(9007199254740991),
          cardType: z.enum(["neutral", "red", "blue", "black"]),
        }),
      ),
      highlights: z.record(
        z.string(),
        z.array(
          z.object({
            playerId: z
              .uuid()
              .regex(
                /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
              ),
            playerName: z.string(),
          }),
        ),
      ),
    }),
    z.null(),
  ]),
  winningSide: z.union([z.enum(["red", "blue"]), z.null()]),
  losingSide: z.union([z.enum(["red", "blue"]), z.null()]),
});

/**
 * CreateGameResponseSchema
 * Response when creating a game
 */
export const zCreateGameResponseSchema = z.object({
  game: zGameSchema,
  creatorToken: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  playerId: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
  gameState: zGameStateSchema,
});

/**
 * GamesSchema
 * Schema for a paginated list of games
 */
export const zGamesSchema = z.object({
  data: z.array(zGameSchema),
  meta: z.object({
    offset: z.number(),
    pageSize: z.number(),
    itemCount: z.number(),
    hasMore: z.boolean(),
  }),
});

/**
 * JoinGameResponseSchema
 * Response when joining a game
 */
export const zJoinGameResponseSchema = z.object({
  gameState: zGameStateSchema,
  playerId: z
    .uuid()
    .regex(
      /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
    ),
});

/**
 * PaginationQuerySchema
 * Schema for pagination query
 */
export const zPaginationQuerySchema = z.object({
  offset: z.int().gte(0).lte(9007199254740991).default(0),
  pageSize: z.int().gte(1).lte(100).default(20),
});

/**
 * SortingQueryStringSchema
 * Schema for sorting items
 */
export const zSortingQueryStringSchema = z.string();

export const zAppControllerGetHelloData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGamesControllerGetGamesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    sort: z.optional(z.string()),
    offset: z.int().gte(0).lte(9007199254740991).default(0),
    pageSize: z.int().gte(1).lte(100).default(20),
  }),
});

/**
 * Schema for a paginated list of games
 */
export const zGamesControllerGetGamesResponse = zGamesSchema;

export const zGamesControllerCreateGameData = z.object({
  body: z.object({
    pseudo: z.string().min(1).max(100),
  }),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response when creating a game
 */
export const zGamesControllerCreateGameResponse = zCreateGameResponseSchema;

export const zGamesControllerGetGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Schema for a game (basic info)
 */
export const zGamesControllerGetGameResponse = zGameSchema;

export const zGamesControllerGetGameStateData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerGetGameStateResponse = zGameStateSchema;

export const zGamesControllerJoinGameData = z.object({
  body: z.object({
    pseudo: z.string().min(1).max(100),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Response when joining a game
 */
export const zGamesControllerJoinGameResponse = zJoinGameResponseSchema;

export const zGamesControllerKickPlayerData = z.object({
  body: z.object({
    creatorToken: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  path: z.object({
    playerId: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerKickPlayerResponse = zGameStateSchema;

export const zGamesControllerLeaveGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerLeaveGameResponse = zGameStateSchema;

export const zGamesControllerChooseSideData = z.object({
  body: z.object({
    side: z.enum(["red", "blue"]),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerChooseSideResponse = zGameStateSchema;

export const zGamesControllerDesignateSpyData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerDesignateSpyResponse = zGameStateSchema;

export const zGamesControllerStartRoundData = z.object({
  body: z.object({
    wordCount: z.optional(z.int().gte(1).lte(400)),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerStartRoundResponse = zGameStateSchema;

export const zGamesControllerGiveClueData = z.object({
  body: z.object({
    word: z.string().min(1),
    number: z.int().gte(0).lte(9007199254740991),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerGiveClueResponse = zGameStateSchema;

export const zGamesControllerSelectWordData = z.object({
  body: z.object({
    wordIndex: z.int().gte(0).lte(9007199254740991),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerSelectWordResponse = zGameStateSchema;

export const zGamesControllerHighlightWordData = z.object({
  body: z.object({
    wordIndex: z.int().gte(0).lte(9007199254740991),
  }),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerHighlightWordResponse = zGameStateSchema;

export const zGamesControllerUnhighlightWordData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    wordIndex: z.int().gte(0).lte(9007199254740991),
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerUnhighlightWordResponse = zGameStateSchema;

export const zGamesControllerPassTurnData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerPassTurnResponse = zGameStateSchema;

export const zGamesControllerRestartGameData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z
      .uuid()
      .regex(
        /^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$/,
      ),
  }),
  query: z.optional(z.never()),
});

/**
 * Full game state computed from events
 */
export const zGamesControllerRestartGameResponse = zGameStateSchema;

export const zWordsControllerGetRandomWordsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    count: z.string(),
  }),
});

/**
 * Schema for a list of words
 */
export const zWordsControllerGetRandomWordsResponse = zWordsSchema;
